# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstmQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_identifier', models.CharField(max_length=16)),
                ('aliquot_identifier', models.CharField(max_length=16)),
                ('query_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
